import { Ubuntu } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
const ubuntu = Ubuntu({ subsets: ["latin"],weight:'400', });

export const metadata = {
  title: "AnimeGab",
  description: "Generated by Gabriel",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`bg-main-dark ${ubuntu.className}`}>
        {<Navbar />}
        {children}
        {<Footer />}
      </body>
    </html>
  );
}
